### ISSUE TITLE
使用最新版本preset初始化项目安装依赖失败

### ISSUE THREAD

**Issue by evanlia** [awesome-starter/create-preset#35]
node版本: v18.17.1, 全局安装脚手架，0.13.1版本，初始化项目过程 preset init -> <project name> -> vue -> vue3-ts-vite, 然后进入项目安装依赖报错，以下是报错内容
While resolving: test@0.0.0
npm ERR! Found: unocss@0.55.2
npm ERR! node_modules/unocss
npm ERR!   dev unocss@"^0.55.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer unocss@"^0.54.1" from @bassist/uno@0.1.2
npm ERR! node_modules/@bassist/uno
npm ERR!   dev @bassist/uno@"^0.1.2" from the root project

应该是项目根目录的unocss和@bassist/uno@0.1.2里的冲突了，手动将package.json中的unocss改成"^0.54.1"可以正常安装依赖并启动

**Comment by chengpeiquan** [comment]
谢谢！是 @bassist/uno 的对等依赖版本限制没有配置成 >= ，已经发布 [0.1.3](https://github.com/chengpeiquan/bassist/commit/346271e0edc0efee63016f10be5164c78f41e3b8) 版本修正了，vue3-ts-vite 里的依赖也已更新
