### ISSUE TITLE
git 提交不了

### ISSUE THREAD

**Issue by Chefback** [awesome-starter/create-preset#36]
lint-staged 无法提交代码 this.options.fields ??= {};SyntaxError: Unexpected token '??= 

查了lint-staged issues [https://github.com/okonet/lint-staged/issues/1315](url)

把node升级到v16和18都报错

**Comment by chengpeiquan** [comment]
这么奇怪… 用了 lint-staged 好久我也没遇到这个情况，先把 package.json 里 `simple-git-hooks` 的相关配置 ，以及 .git/hooks/pre-commit 文件里涉及的 `lint-staged` 命令先注释掉吧，先把提交功能恢复起来，我这几天二阳了状态不太行，回头我再研究下是咋回事~

**Comment by Chefback** [comment]
行谢谢回复，多加休息

**Comment by chengpeiquan** [comment]
Hi , 之前用的 simple-git-hooks 需要在 package.json 配置，出问题又需要到 .git/hooks 文件夹里删掉对应的钩子文件（或者重新之前依赖安装触发 simple-git-hooks 的重新写入），总的来说学习成本或者维护成本都还是比较高。

Vue 的 Starter 我改成用 Husky 作为 Git Hooks 管理器了，也简单写了一点 [README 说明](https://github.com/awesome-starter/vue3-ts-vite-starter/tree/master/.husky) ，只需要通过 Husky 的命令，在 `.husky` 文件夹里就可以管理这些钩子，相比 simple-git-hooks 方便很多。

这个 issue 我也触发不出来这个情况，如果还一直遇到的话可以到 lint-staged 的仓库问问作者，我这边先关了哈，如果对 Git Hooks 的操作有什么问题也可以再找我~
